// Package config manages ClawWork CLI configuration files.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// Config holds all ClawWork CLI settings.
type Config struct {
	Agent   AgentConfig   `toml:"agent"`
	LLM     LLMConfig     `toml:"llm"`
	Logging LoggingConfig `toml:"logging"`
}

// AgentConfig holds agent identity and inscription target.
type AgentConfig struct {
	Name    string `toml:"name"`
	APIKey  string `toml:"api_key"`
	TokenID int    `toml:"token_id"`
}

// LLMConfig holds LLM provider settings.
type LLMConfig struct {
	Provider string `toml:"provider"`
	BaseURL  string `toml:"base_url"`
	APIKey   string `toml:"api_key"`
	Model    string `toml:"model"`
}

// LoggingConfig holds logging settings.
type LoggingConfig struct {
	Level string `toml:"level"`
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig() *Config {
	return &Config{
		Agent:   AgentConfig{TokenID: 42},
		LLM:     LLMConfig{Provider: "openai", BaseURL: "https://api.moonshot.cn/v1", Model: "kimi-k2.5"},
		Logging: LoggingConfig{Level: "info"},
	}
}

// Dir returns the config directory path.
// Uses CLAWWORK_HOME env var if set, otherwise defaults to ~/.clawwork.
func Dir() string {
	if d := os.Getenv("CLAWWORK_HOME"); d != "" {
		return d
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".clawwork")
}

// Path returns the config file path.
func Path() string {
	return filepath.Join(Dir(), "config.toml")
}

// Load reads config from disk. Returns an error if the file does not exist.
func Load() (*Config, error) {
	cfg := DefaultConfig()
	_, err := toml.DecodeFile(Path(), cfg)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("config not found — run 'clawwork init' first")
		}
		return nil, fmt.Errorf("failed to read config: %w", err)
	}
	return cfg, nil
}

// Save writes the config to disk with restricted permissions.
func (c *Config) Save() error {
	dir := Dir()
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}
	f, err := os.OpenFile(Path(), os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}
	defer f.Close()

	_, _ = fmt.Fprintln(f, "# ClawWork configuration")
	_, _ = fmt.Fprintln(f, "# Generated by: clawwork init")
	_, _ = fmt.Fprintln(f)
	return toml.NewEncoder(f).Encode(c)
}
